name: 'Rotate GCP service account keys'
author: 'Miklos Niedermayer <miklos.niedermayer@aliz.ai>'
description: Github action that rotates gcp service account keys and updates github secret
inputs:
  projectId:
    description: "GCP project id to use"
    required: true
  serviceAccount:
    description: "E-mail id of the service account to act on"
    required: true
  personalAccessToken:
    description: "Github token that can update secrets in the repos"
    required: true
  repositories:
    description: "List of repositories, separated by comma, to install secrets in"
    required: true
  secretName:
    description: "Name of the GH secret"
    required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'check-circle'
    color: 'blue'
